Update util.py
Fix AttributeError: 'function' object has no attribute 'client'
This code is used to create an xmlrpc server, so logically the functions should be imported from xmlrpc.server instead of xmlrpc.client, but I believe they are the same functions made available in both places.